FROM golang:alpine AS builder

WORKDIR /app

COPY main.go /app/main.go
RUN go build -o fullcycle -ldflags "-s -w" main.go

FROM scratch
COPY --from=builder /app/fullcycle /fullcycle

CMD ["/fullcycle"]
